---

units:
   - name: "NetworkManager"
     action: "enable"
     mandatory: true
   - name: "bluetooth"
     action: "enable"
     mandatory: true
   - name: "docker"
     action: "enable"
     mandatory: false
   - name: "seatd"
     action: "enable"
     mandatory: true
   - name: "sddm"
     action: "enable"
     mandatory: true
